In [1]:
from datasets import load_dataset
import pandas as pd 
import matplotlib.pyplot as plt 

#loading data 
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset ['train'].to_pandas()

#data cleaning
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
df.iloc[0:10, 5]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8    False
9     True
Name: job_work_from_home, dtype: bool

In [9]:
df.iloc[0:10, 0:4]

,job_title_short,job_title,job_location,job_via
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter

In [7]:
df.loc[:, 'salary_rate': 'salary_hour_avg' ].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]